### ISSUE TITLE
Unable to run application

### ISSUE THREAD

**Issue by hahne-t** [angadsingh/argos#10]
After running the Docker Container it reflects with missing "SlidingWindowDetectionBuffer"

```docker run --rm -p 8051:8081 -v /home/docker/argos/config:/configs -v /home/docker/argos/detections:/output_detections -v /home/docker/argos/argos-ssh:/root/.ssh angadsingh/argos:x86_64 /usr/src/argos/stream.py --ip 0.0.0.0 --port 8081 --config config_tflite_ssd_stream.py
2022-03-23 12:11:31:INFO:__main__:package import START
2022-03-23 12:11:31:INFO:__main__:package import END
Traceback (most recent call last):
  File "/usr/src/argos/stream.py", line 230, in <module>
    m = importlib.import_module(args["config"])
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/configs/config_tflite_ssd_stream.py", line 5, in <module>
    from lib.detection_buffer import SlidingWindowDetectionBuffer, SimpleDetectionBuffer
ImportError: cannot import name 'SlidingWindowDetectionBuffer'```

**Comment by angadsingh** [comment]
i have made some changes to the codebase but it wasn't pushed to dockerhub. Just updated the docker images with the latest changes: https://hub.docker.com/r/angadsingh/argos/tags

Tested on a fresh environment. its working now.

please delete your local docker images first, and then run/pull again

**Comment by ghost** [comment]
I deleetet the Image. But i get another issue, maybe i'm bad?

```amunre@ubuntu-server:~$ docker run --rm -p 8051:8081 -v /home/docker/argos/config:/configs -v /home/docker/argos/detections:/output_detections -v /home/docker/argos/argos-ssh:/root/.ssh angadsingh/argos:x86_64 /usr/src/argos/stream.py --ip 0.0.0.0 --port 8081 --config config_tflite_ssd_stream.py
Unable to find image 'angadsingh/argos:x86_64' locally
x86_64: Pulling from angadsingh/argos
08c01a0ec47e: Already exists
40cafd7aa541: Pull complete
732cfa28efdb: Pull complete
59d18cda6101: Pull complete
2156f513935e: Pull complete
93dabc744765: Pull complete
b29430bf196e: Pull complete
de3708851a6c: Pull complete
6586aa26e2e9: Pull complete
4f4fb700ef54: Pull complete
6bf8c00dd94f: Pull complete
40e023a70723: Pull complete
dd17f12dba7d: Pull complete
b23e71c67b78: Pull complete
1aeb32fb85b8: Pull complete
071998f9bc2f: Pull complete
287adc30a043: Pull complete
a34a07143d71: Pull complete
Digest: sha256:6a4e2a5e0645d501f6f3fb9f7d4ee9bbbcbb0e33de2b193008c4ed25c3d232e0
Status: Downloaded newer image for angadsingh/argos:x86_64
2022-03-25 21:09:18:INFO:__main__:package import START
2022-03-25 21:09:18:INFO:__main__:package import END
Traceback (most recent call last):
  File "/usr/src/argos/stream.py", line 232, in <module>
    m = importlib.import_module(args["config"])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config_tflite_ssd_stream.py'; 'config_tflite_ssd_stream' is not a package
```

**Comment by angadsingh** [comment]
remove '.py' from config file name in the run command. if it still doesn't work, please paste the run command here.
