### ISSUE TITLE
Error loading config file

### ISSUE THREAD

**Issue by edalquist** [angadsingh/argos#5]
I created my own stream config via: `$ cp configs/examples/config_tflite_ssd_stream.py configs/driveway_stream.py` modified the file and then when I run stream.py I get:

```
(argos-venv) edalquist@argos:~/argos$ python stream.py --ip 0.0.0.0 --port 8080 --config config.driveway_stream
INFO:__main__:package import START
INFO:__main__:package import END
Traceback (most recent call last):
  File "stream.py", line 229, in <module>
    m = importlib.import_module(args["config"])
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config'
```

**Comment by edalquist** [comment]
And as soon as I posted I realized I had config not configs

**Comment by angadsingh** [comment]
np. do let me know how it works out for you
